name: 编译多架构的2.8.x多线程

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TZ: Asia/Shanghai
permissions:
  contents: write
  actions: write 
jobs:
  build:
    name: ${{ matrix.TARGET }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: aarch64-linux-musl
            OPENSSL_TARGET: linux-aarch64
          - TARGET: armv7l-linux-musleabihf
            OPENSSL_TARGET: linux-armv4
          - TARGET: armv7m-linux-musleabi
            OPENSSL_TARGET: linux-armv4
          - TARGET: arm-linux-musleabi
            OPENSSL_TARGET: linux-armv4
          - TARGET: arm-linux-musleabihf
            OPENSSL_TARGET: linux-armv4
          - TARGET: mipsel-linux-muslsf
            OPENSSL_TARGET: linux-mips32
          - TARGET: mips-linux-muslsf
            OPENSSL_TARGET: linux-mips32
          - TARGET: i686-linux-musl
            OPENSSL_TARGET: linux-generic32
          - TARGET: x86_64-linux-musl
            OPENSSL_TARGET: linux-x86_64
    runs-on: ubuntu-latest
    env:
      OPENSSL_TARGET: ${{ matrix.OPENSSL_TARGET }}
      TARGET: ${{ matrix.TARGET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 缓存 OpenSSL 
        id: cache-openssl
        uses: actions/cache@v4
        with:
          path: |
            /opt/openssl-${{ env.TARGET }}
          key: openssl-${{ env.TARGET }}-cache
      - name: 下载编译工具链
        run: |
          mkdir -p /opt/musl_gcc 
          sudo timedatectl set-timezone "Asia/Shanghai"
          #下载编译器
          wget -q -c https://musl.cc/${{ env.TARGET }}-cross.tgz -P /opt/musl_gcc/
          tar zxf /opt/musl_gcc/${{ env.TARGET }}-cross.tgz -C /opt/musl_gcc/
          
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.2.4
          install-only: true
      - name: 编译
        run: |
          export PATH=/opt/musl_gcc/${{ env.TARGET }}-cross/bin:$PATH
          export CC=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-gcc
          export CXX=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-g++
          export AR=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-ar
          export LD=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-ld
          export RANLIB=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-ranlib
          export STRIP=/opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip

          if [ ! -d "/opt/openssl-${{ env.TARGET }}" ]; then
            #克隆openssl
            git clone --recursive https://github.com/openssl/openssl -b OpenSSL_1_1_1-stable
            cd openssl
            echo "###########################编译openssl依赖库########################"
            ./Configure no-shared no-zlib --prefix=/opt/openssl-${{ env.TARGET }} ${{ env.OPENSSL_TARGET }} LDFLAGS="-static -I/opt/musl_gcc/${{ env.TARGET }}-cross/${{ env.TARGET }}/include -L/opt/musl_gcc/${{ env.TARGET }}-cross/${{ env.TARGET }}/lib" CFLAGS="-static -I/opt/musl_gcc/${{ env.TARGET }}-cross/${{ env.TARGET }}/include -L/opt/musl_gcc/${{ env.TARGET }}-cross/${{ env.TARGET }}/lib"
            make -j$(nproc)
            make install
            cd ../
          fi
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_CXX_COMPILER=${CXX} \
            -DCMAKE_AR=${AR} \
            -DCMAKE_LINKER=${LD} \
            -DCMAKE_RANLIB=${RANLIB} \
            -DCMAKE_C_COMPILER_AR=${AR} \
            -DCMAKE_C_COMPILER_RANLIB=${RANLIB} \
            -DCMAKE_CXX_COMPILER_AR=${AR} \
            -DCMAKE_CXX_COMPILER_RANLIB=${RANLIB} \
            -DCMAKE_STRIP=${STRIP} \
            -DOPENSSL_ROOT_DIR=/opt/openssl-${{ env.TARGET }} \
            -DOPENSSL_USE_STATIC_LIBS=TRUE \
            -DHAVE_OPENSSL_1_1 \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" 

          make -j$(nproc)
          
        #continue-on-error: true
      - 
        name: 剥离压缩
        run: |
          cd build
          #查看当前目录文件
          ls -la
          #查看edge二进制文件信息
          file edge
          #剥离
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip edge
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip example_edge_embed
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip example_edge_embed_quick_edge_init
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip example_sn_embed
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip supernode
          /opt/musl_gcc/${{ env.TARGET }}-cross/bin/${{ env.TARGET }}-strip n2n-benchmark
          #压缩
          upx --lzma --best edge
          upx --lzma --best example_edge_embed
          upx --lzma --best example_edge_embed_quick_edge_init
          upx --lzma --best example_sn_embed
          upx --lzma --best supernode
          upx --lzma --best n2n-benchmark
          zip n2n-pthread-${{ env.TARGET }}.zip edge example_edge_embed example_edge_embed_quick_edge_init example_sn_embed supernode n2n-benchmark
          tagtime=$(date '+%Y-%m-%d')
          echo "tagtime=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV

      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: n2n-pthread-${{ env.TARGET }}
         path: |
           build/edge
           build/example_edge_embed
           build/example_edge_embed_quick_edge_init
           build/example_sn_embed
           build/supernode
           build/n2n-benchmark
      - name: 发布
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
           > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ env.tagtime }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github)
           
          tag_name: ${{ env.tagtime }}
          files: build/n2n-pthread-${{ env.TARGET }}.zip
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 2
        keep_minimum_runs: 2 
